### ISSUE TITLE
Cant get it to validate tickets - bug ?

### ISSUE THREAD

**Issue by cousinsa** [gstrauss/lighttpd-mod_authn_tkt#1]
Have had no successes in validating tickets. 
On examining source code it appears  line 264 (in digest_hex_to_bin()  ) might be incorrect.

This will never  execute the loop ?

for (size_t i = inlen; i < inlen; i+=2) {

I think it should start at 0.
I'm not in a position to rebuild at the moment. Will try asap.

**Comment by gstrauss** [comment]
Agreed.  That looks wrong.

lighttpd 1.4.56 was just released, and is incompatible with lighttpd modules written for earlier releases.

I just pushed an updated mod_authn_tkt.c to build with lighttpd 1.4.56, but it is not well tested.  However, the latest push already fixes the issue your reported above.

**Comment by gstrauss** [comment]
@cousinsa this issue should be fixed with the recently updated lighttpd-mod_authn_tkt for lighttpd 1.4.56.  I am going to close this issue, but if you have new problems with lighttpd 1.4.56, please open a new issue.
