### ISSUE TITLE
Problems/Bug in finding cookie.

### ISSUE THREAD

**Issue by cousinsa** [gstrauss/lighttpd-mod_authn_tkt#3]
Found a problem in parsing the header. Cookies are separated by ';' but there can also be spaces. 
If the authn_tkt is not first it never finds it as it includes the space in the string to be matched.
eg:
auth_tkt_back=https://nnn.nnn.nnn.nnn%2Fpgs%2FAbout.html;  auth_tkt="MTg3NWM0...etc...XxpLG4hSE9MQQ=="

I did a quick fix to this routine ......

/* Search cookie headers for our ticket */
static int authn_tkt_from_cookie(request_st * const r, mod_authn_tkt_plugin_data * const p)/*{{{*/
{
    const buffer * const name = p->conf.auth_opts->auth_cookie_name;
    const size_t nlen = buffer_string_length(name);
    const buffer * const hdr =
      http_header_request_get(r, HTTP_HEADER_COOKIE, CONST_STR_LEN("Cookie"));
    if (NULL == hdr) return 0;
    for (const char *start=hdr->ptr, *semi, *end; *start; start = semi+1) {
        while (' ' == *start) start++;                               // *********** quick bug fix - cookies can have spaces between them
        semi = strchr(start+1, ';');

Chrome on Windows 10 and lighted on gentoo-4.19

**Comment by gstrauss** [comment]
Thank you.  I'll take a closer look at this tomorrow and will incorporate your fix.

**Comment by gstrauss** [comment]
Patched and pushed.  Thank you!
