### ISSUE TITLE
sha256 and sha512 can't be configured.

### ISSUE THREAD

**Issue by cousinsa** [gstrauss/lighttpd-mod_authn_tkt#4]
The section of code between lines 985 and 1006 where the digest type is set up is not correct. 
md5sum will always be used regardless of configuration.

The "if" tests for checking the digest types are inverted they are testing for string not equal. 
These lines should be  !=   or  1==   or just the function call?

line 989:    if (0 == buffer_is_equal_string(cpv-&gt;v.b,  CONST_STR_LEN(""))
line 995:    else if (0 == buffer_is_equal_string(cpv-&gt;v.b,  CONST_STR_LEN("SHA256"))) 
line 1002:  else if (0 == buffer_is_equal_string(cpv-&gt;v.b,  CONST_STR_LEN("SHA512"))) 

also line 989 should cover default case and md5. I changed mine to

if (buffer_is_equal_string(csv->v.b, CONST_STR_LEN(""))
        || buffer_is_equal_string(csv->v.b, CONST_STR_LEN("MD5")))

**Comment by gstrauss** [comment]
Thanks for pointing it out.  Fix will be pushed momentarily.

The default is MD5, and that is all that is currently supported by most modern browsers.  Only Opera supports SHA-256, though Mozilla recently incorporated some patches I submitted, so Firefox 90, scheduled for release in mid-July, should have new support for SHA-256.  https://bugzilla.mozilla.org/show_bug.cgi?id=472823

https://redmine.lighttpd.net/projects/lighttpd/wiki/Docs_ModAuth#Warning
